### ISSUE TITLE
where is the backbone pretrained model?

### ISSUE THREAD

**Issue by Byronnar** [feiyuhuahuo/SOLOv2_minimal#3]
Could you please provide the backbone pretrained model (weights/backbone_resnet34.pth)? I want to train coco dataset, Looking forward to your reply, thx.

**Comment by feiyuhuahuo** [comment]
I uploaded. https://github.com/feiyuhuahuo/SOLOv2_minimal/releases/tag/v1.0

**Comment by Byronnar** [comment]
> I uploaded. https://github.com/feiyuhuahuo/SOLOv2_minimal/releases/tag/v1.0

Thank you so much!  By the way, I tried to convert the pytorch model to onnx, but I encountered some problems, the error is as follows:
```
ther case, this might cause the trace to be incorrect.
  x = (x - torch.tensor([127., 127., 127.], device='cuda')) / torch.tensor([60., 60., 60.], device='cuda')
/opt/conda/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:2966.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "export2onnx.py", line 30, in <module>
    torch.onnx.export(model,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 479, in export
    _export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1411, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1054, in _model_to_graph
    graph = _optimize_graph(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 550, in _optimize_graph
    _C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple index with non-constant index

```,  Can you provide some help？

**Comment by feiyuhuahuo** [comment]
Can your model reach this line when exporting? https://github.com/feiyuhuahuo/SOLOv2_minimal/blob/e1d81cfb8beb16d6675a3b701963a70919eed814/model/head.py#L466

**Comment by Byronnar** [comment]
> Can your model reach this line when exporting?
> 
> https://github.com/feiyuhuahuo/SOLOv2_minimal/blob/e1d81cfb8beb16d6675a3b701963a70919eed814/model/head.py#L466

Yes, I can reach there:
```
get_seg = torch.jit.script(get_seg_scripted)
        seg_result = get_seg(cate_preds, kernel_preds, mask_feat_pred)
        # print("seg_result: ", seg_result)
```,  get the seg_result success.

**Comment by Byronnar** [comment]
I have solved this problem, But I can't convert onnx to tensorrt...

**Comment by feiyuhuahuo** [comment]
TensorRT C++ API or Python API？

**Comment by Byronnar** [comment]
> 
For Python, This code not support in tensorrt (DynamicConv):
```
seg_preds = F.conv2d(seg_preds, kernel_preds, stride=1).squeeze(0).sigmoid() 
```
Can you convert tensorrt success??

**Comment by Byronnar** [comment]
The logs as below:
```
[07/21/2023-07:43:51] [E] [TRT] ModelImporter.cpp:726: While parsing node number 413 [Conv -> "onnx::Squeeze_1420"]:
[07/21/2023-07:43:51] [E] [TRT] ModelImporter.cpp:727: --- Begin node ---
[07/21/2023-07:43:51] [E] [TRT] ModelImporter.cpp:728: input: "onnx::Conv_1159"
input: "onnx::Conv_1419"
output: "onnx::Squeeze_1420"
name: "Conv_915"
op_type: "Conv"
attribute {
  name: "dilations"
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "group"
  i: 1
  type: INT
}
attribute {
  name: "kernel_shape"
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "pads"
  ints: 0
  ints: 0
  ints: 0
  ints: 0
  type: INTS
}
attribute {
  name: "strides"
  ints: 1
  ints: 1
  type: INTS
}

[07/21/2023-07:43:51] [E] [TRT] ModelImporter.cpp:729: --- End node ---
[07/21/2023-07:43:51] [E] [TRT] ModelImporter.cpp:732: ERROR: onnx2trt_utils.cpp:2060 In function convMultiInput:
[8] Assertion failed: layer && "Failed to add the Convolution layer."
```

**Comment by Byronnar** [comment]
The tensorrt deploy is diffucult. About the training problem, Could you please tell me the code below can be detele? 
```
    def train(self, mode=True): 
        super(ResNet, self).train(mode)
        self._freeze_stages() 
        if mode and self.norm_eval:
            for m in self.modules():
                # trick: eval have effect on BatchNorm only
                if isinstance(m, _BatchNorm):   # This line
                    m.eval()
```, 
When I delete this code(m.eval()), mAP is low.... 
But for some reason I'm going to delete it and use another BackBone. Or when I delete these codes, is there any other places that can be modified to improve the accuracy, looking forward to your reply.

**Comment by feiyuhuahuo** [comment]
Some parameters are different during training and evaling. So use module.train() and module.eval() to control it. Set module.train() when evaling certainly cause low mAP.

**Comment by Byronnar** [comment]
OK， Thank you
